stages:
  prepare:
    cmd: python src/process_data.py
    deps:
      - data/dataset.csv
    outs:
      - data/processed_train_data.csv
      - data/processed_test_data.csv
    params: 
      - features.test_size
      - features.val_size
      - features.data_path
